### ISSUE TITLE
Arrow pointing the wrong way

### ISSUE THREAD

**Issue by fredley** [dbushong/shaky#1]
![bug](https://cloud.githubusercontent.com/assets/270631/10137371/0e729da8-65f1-11e5-85a8-4aa7153c3259.png)

**Comment by dbushong** [comment]
I just copied the logic from somewhere else.  IIRC the rule is that you can't have mid-line arrows, and since there's already an endpoint on each end (bulb on one, arrow on the other), the behavior is Undefined.
